network_identifier:
  blockchain: IoTeX
  network: testnet
currency:
  symbol: IOTX
  decimals: 18
server:
  port: 8080
  endpoint: api.testnet.iotex.one:443
  secureEndpoint: true
  rosettaVersion: 1.3.5
pacificBlockHeight: 432001